* EC key generation
:PROPERTIES:
:TOC: :include descendants
:END:

:CONTENTS:
:END:

** Concepts and purpose

*** secp256k1 private key

- secp256k1 private key :: A secp256k1 private key ~k = keccak256(CSPRNG(256
  bits))~ is a 32 bytes random large integer generated by a cryprographically
  secure pseudo-random number generator CSPRNG with 256 bits of entropy e.g.
  tossing a coin 256 times. A private key is used to derive the corresponding
  public key and sign transactions to spend funds from an externally owned
  account EOA or to authenticate users against smart contracts in order to
  invoke smart contract functions from an EOA. A private key is the only piece
  of information required to fully control an EOA. If a private key is lost, the
  funds associated with an EOA are lost forever

*** secp256k1 public key

- secp256k1 public key :: A secp256k1 private key ~K = (x, y) = k x G~ is a
  point with two 32 bytes coordinates ~(x, y)~ on the secp256k1 elliptic curve
  derived from a private key =k= by multiplying the private key by the generator
  point =const G= defined in a standard. The generator point is the same for all
  keys. A public key is used to derive the address of an EOA and to verify
  transaction signatures produced with the corresponding private key. It is
  unfeasible to compute a private key from the corresponding public key
  - Uncompressed public key :: An 65 bytes uncompressed public key ~K = 0x04 +
    x + y~ is the concatenation of the two 32 bytes coordinates ~(x, y)~
    prefixed with the =0x04= prefix
  - Compressed public key :: A 33 bytes compressed public key ~K = 0x02 y even |
    0x03 y odd + x~ is only the 32 bytes =x= coordinate prefixed with either
    =0x02= prefix if the =y= coordinate is even or =0x03= prefix if the =y=
    coordinate is odd. The y coordinate can be unambiguously derived from the x
    coordinate and the parity prefix

*** Ethereum address

- Ethereum address :: An Ethereum address ~a = keccak256(K)[12:]~ is the last 20
  bytes of the Keccak256 hash of the uncompressed public key without the =0x04=
  prefix

** Design and implementation

** Testing and usage
